name: "Code Quality"

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-jvm
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          publish_branch: gh-pages
          destination_dir: ./qodana
